# Generated by Django 6.0.2 on 2026-02-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_booked_at_alter_timeslot_doctor'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('doctor', 'date', 'start_time'), name='unique_slot'),
        ),
    ]
