# Generated by Django 6.0.2 on 2026-02-13 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_timeslot_unique_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot', unique=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='day',
            field=models.DateField(),
        ),
    ]
