# Generated by Django 6.0.2 on 2026-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='max_patients_per_slot',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
